name: text_tune
description: "Um aplicativo multiplataforma para reescrever textos usando IA da Abacus"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.13.6
  dio: ^5.3.2
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.0
  fluttertoast: ^8.2.4
  font_awesome_flutter: ^10.6.0
  google_fonts: ^6.3.0
  google_sign_in: ^6.1.6
  http: ^1.1.0
  intl: ^0.18.1
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  sign_in_with_apple: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  