name: text_tune
description: "Um aplicativo multiplataforma para reescrever textos usando IA da Abacus"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cloud_firestore: ^6.0.0
  firebase_analytics: ^12.0.0
  firebase_auth: ^6.0.1
  firebase_core: ^4.0.0
  firebase_remote_config: ^6.0.0
  flutter:
    sdk: flutter
  google_fonts: ^6.3.0
  google_sign_in: ^7.1.1
  http: ^1.5.0
  intl: ^0.20.2
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  sign_in_with_apple: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  